# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.gathering.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - run:
          sudo apt update && sudo apt install -y jq
      - id: gathering
        run: |
          find -name '*.txt' | jq -R . | jq -s .
          echo "::set-output name=files::$(find -name '*.txt' | jq -R . | jq -c -s .)"
  cat:
    runs-on: ubuntu-latest
    needs: [ files ]
    strategy:
      matrix:
        file: ${{ fromJson(needs.files.outputs.files) }}
    steps:
      - uses: actions/checkout@v3
      - name: cat
        run: cat ${{ matrix.file }}
